(function () {
    'use strict';
    angular
        .module('app')
        .constant('localizations', {
            en: {
                SEARCHPLACEHOLDER: 'Search or add new thread here',
                SETTINGS: 'Settings',
                DOLOGIN: 'Login',
                LOGIN: 'Login',
                PROFILE: 'Profile',
                LOGOUT: 'Logout',
                WIKI: 'Wiki',
                FAQ: 'FAQ',
                DISCUSSION: 'Discussion',
                ADDCOMMENT: 'Add comment',
                GUEST: 'Guest',
                EXPAND: 'Expand',
                COLLAPSE: 'Collapse',
                DOANSWER: 'Answer',
                WRITECOMMENTHERE: 'Write your comment here...',
                SEND: 'Send',
                CLOSE: 'Close',
                USERNAME: 'User name',
                PASSWORD: 'Password',
                REMEMBERME: 'Remember me',
                LOGINUSINGEXTERNALSERVICES: 'Login using external services:',
                MAKEREGISTER: 'Register',
                DOREGISTER: 'Register',
                IFYOUDONTHAVEACCOUNT: ', if you don\'t have account',
                CANCEL: 'Cancel',
                LOGINFAILED: 'Login failed!',
                REGISTRATIONFAILED: 'Registration failed!',
                CONFIRMPASSWORD: 'Confirm password',
                ACCEPT: 'Accept',
                TERMS: 'terms',
                REGISTER: 'Register',
                REGISTRATION: 'Registration',
                ADDCOMMENTFAILED: 'Adding comment failed!',
                OK: 'OK',
                WARNING: 'Warning',
                WAITBEFORENEWCOMMENT: 'Wait {{delay}} before applying a new comment',
                ADD: 'Add',
                SAVEQUESTIONFAILED: 'Save question failed!',
                QUESTION: 'Question:',
                ANSWER: 'Answer:',
                EDIT: 'Edit',
                DEFAULTBANNER: 'Like comments? install extension!',
                ADDTHREAD: 'Add thread: ',
                SETLINK: 'Set link',
                EDITTEXT: 'Edit text',
                DOMODERATE: 'Moderate',
                REMOVE: 'Remove',
                MODERATEFAILED: 'Moderate comment failed!',
                PENALTY: 'Penalty',
                MESSAGEDELETEDBY: 'Message deleted by',
                MODERATE: 'Moderate',
                RENAMETHREAD: 'Rename thread:',
                RENAME: 'Rename',
                ADDCOMMENTFORNOTAUTHORIZEDMSG: 'Login to add comment'
            },
            ru: {
                SEARCHPLACEHOLDER: 'Найти тему или напишите название новой темы обсуждения здесь',
                SETTINGS: 'Настройки',
                DOLOGIN: 'Войти',
                LOGIN: 'Вход',
                PROFILE: 'Учётная запись',
                LOGOUT: 'Выйти',
                WIKI: 'Вики',
                FAQ: 'ЧАВО',
                DISCUSSION: 'Обсуждение',
                ADDCOMMENT: 'Написать новый комментарий',
                GUEST: 'Гость',
                EXPAND: 'Развернуть',
                COLLAPSE: 'Свернуть',
                DOANSWER: 'Ответить',
                WRITECOMMENTHERE: 'Напишите комментарий здесь...',
                SEND: 'Отправить',
                CLOSE: 'Закрыть',
                USERNAME: 'Имя пользователя',
                PASSWORD: 'Пароль',
                REMEMBERME: 'Запомнить меня',
                LOGINUSINGEXTERNALSERVICES: 'Войти используя:',
                MAKEREGISTER: 'Зарегистрируйтесь',
                DOREGISTER: 'Зарегистрироваться',
                IFYOUDONTHAVEACCOUNT: ', если у вас нет аккаунта',
                CANCEL: 'Отмена',
                LOGINFAILED: 'Ошибка входа!',
                REGISTRATIONFAILED: 'Ошибка регистрации!',
                CONFIRMPASSWORD: 'Подверждение пароля',
                ACCEPT: 'Я принимаю',
                TERMS: 'условия использования',
                REGISTER: 'Зарегистрироваться',
                REGISTRATION: 'Регистрация',
                ADDCOMMENTFAILED: 'Ошибка при добавлении комментария!',
                OK: 'OK',
                WARNING: 'Внимание',
                WAITBEFORENEWCOMMENT: 'Ожидание перед написанием нового комментария: {{delay}}',
                ADD: 'Добавить',
                SAVEQUESTIONFAILED: 'Не удалось сохранить вопрос!',
                QUESTION: 'Вопрос:',
                ANSWER: 'Ответ:',
                EDIT: 'Редактировать',
                DEFAULTBANNER: 'Хотите иметь возможность комментировать везде? Установите расширение в браузер!',
                ADDTHREAD: 'Добавить тему обсуждения: ',
                SETLINK: 'Установить ссылку',
                EDITTEXT: 'Редактировать текст',
                DOMODERATE: 'Модерировать',
                REMOVE: 'Удалить',
                MODERATEFAILED: 'Не удалось модерировать комментарий!',
                PENALTY: 'Штраф',
                MESSAGEDELETEDBY: 'Комментарий удалён модератором',
                MODERATE: 'Модерация',
                RENAMETHREAD: 'Переименовать тему:',
                RENAME: 'Переименовать',
                ADDCOMMENTFORNOTAUTHORIZEDMSG: 'Войдите, чтобы оставить комментарий'                
            }
        });
})();